### ISSUE TITLE
[Theos Builder] Missing value in variables array for shell wildcard (+ another)

### ISSUE THREAD

**Issue by RedenticDev** [DragonBuild/dragon#106]
My prefs module contains a lot of files in a lot of subdirs, so I use `$(BUNDLE_NAME)_FILES = $(shell find . -type f -name "*.m")` to compile them all but DragonGen doesn't seem to be able to handle that  

Also when using a `DragonMake` file I've got an error "An undocumented error has been hit, Please contact a maintainer" in `Check YAML syntax of fill an issue` (typo on that btw, it tells `file an issue`).  
My `DragonMake` (Theos stuff there, including `Makefile`, `layout` folder, `control` file etc):
```yaml
---
all:
  archs:
    - arm64
    - arm64e
  targetvers: 13.3

Tweak:
  type: tweak
  files:
    - *.x
    - *.m
    - *.mm
  cflags: -include ../Prefix.h
  libs:
    - colorpicker
  frameworks:
    - IOKit
    - BluetoothManager

Preferences:
  type: prefs
  files:
    - *.m
    - "**/*.m"
  cflags: -include ../Prefix.h
  libs:
    - colorpicker
  frameworks:
    - Preferences
    - OnBoardingKit
    - Cephei
    - CepheiPrefs
  stage:
    - mkdir -p .dragon/_/Library/PreferenceLoader/Preferences
    - cp entry.plist .dragon/_/Library/PreferenceLoader/Preferences/Sepiida.plist
```
> I also keep having issues with Theos ("cannot build module 'Foundation'") on that new M1 Mac, and now I also have issue with dragon, I literally cannot build tweaks anymore iwannadie
