### ISSUE TITLE
Preferences don't work

### ISSUE THREAD

**Issue by monotrix** [DragonBuild/dragon#51]
I tried to install a freshly built tweak on my iPhone 7 Plus after building it from my M1 Macbook Pro, and the preferences didn't work.

I think it's fair to note that another tweak of mine that doesn't have preferences, when built and installed from and on the same devices, works just fine.

Here is the source code if necessary:

https://github.com/monotrix/Open-Sourced-Tweaks/tree/master/ReachOptions

**Comment by quiprr** [comment]
This is likely due to your toolchain.

**Comment by monotrix** [comment]
What would you recommend I do to fix it? I noticed that others commenting on my release post about the tweak were experiencing this issue as well, although my initial testers didn't...

**Comment by KritantaDev** [comment]
If you can send me a .deb for your tweak I'll take a look at this as soon as I can.

**Comment by monotrix** [comment]
Sure thing, here it is:

https://gofile.io/d/Kl73Si

**Comment by KritantaDev** [comment]
quick fix:
```
ReachOptions:
  dir: Tweak
  type: tweak
  files:
    - ReachOptions.xm
    - Actions.xm
    - UIDevice+notchedDevice.m

Preferences:
  dir: Preferences
  type: prefs
  files:
    - ROPRootListController.m
```

Seems like the globbing (*.xm) isn't working at all, gonna try and figure this out
